spring.application.name=money_manager
server.port=9090
# MySql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/project
spring.datasource.username=root
spring.datasource.password=Dipak1219.
server.servlet.context-path=/api/v2.0
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Email Configuration
spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=2525
spring.mail.port=587
# write login here
spring.mail.username=a075b4001@smtp-brevo.com
#Key of generated new SMTP.
spring.mail.password=${MAIL_PASSWORD:xsmtpsib-735fddb3a69a4fd7f9b83d71277e4dfca4a7147cb3c77f121e44e3c45e3fdc4a-nB74SKZvfPtH7OeS}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# login email
spring.mail.properties.mail.smtp.from=${LOGIN_MAIL:deepakchavan1219@gmail.com}
# Turn this on to see the exact error in your console => use it only for more details.
#spring.mail.properties.mail.debug=true


# frontend url
money.manager.frontend.url=${FRONTEND_URL:http://localhost:5173}
app.activation.url=${BACKEND_URL:http://localhost:9090}

spring.profiles.active=prod