spring.datasource.url=jdbc:postgresql://dpg-d69lfh14tr6s73co5sr0-a.singapore-postgres.render.com/money_manager_121_xarn
spring.datasource.username=money_manager_121_xarn
spring.datasource.password=LumfpqneIKfK2jWFGQqzoXXP7ecfgfPt