spring.datasource.url=jdbc:postgresql://dpg-d6is8g5m5p6s73dvm6mg-a.singapore-postgres.render.com:5432/finance_tracker_t7u3 
spring.datasource.username=finance_tracker_t7u3_user
spring.datasource.password=UyGpu4nkFA6eHdR7HYcezRm7lqV5fTtz
#jdbc:postgresql://dpg-d6is8g5m5p6s73dvm6mg-a.singapore-postgres.render.com/finance_tracker_t7u3_user
#spring.datasource.url=jdbc:postgresql://dpg-d69lfh14tr6s73co5sr0-a.singapore-postgres.render.com/money_manager_121_xarn
#spring.datasource.username=money_manager_121_xarn
#spring.datasource.password=LumfpqneIKfK2jWFGQqzoXXP7ecfgfPt