spring.datasource.url=jdbc:postgresql://dpg-d5ntb6m3jp1c73eo8ea0-a.singapore-postgres.render.com/money_manager_121
spring.datasource.username=money_manager_121_user
spring.datasource.password=EsAmQTEF1WPJBlTmc4I8uXoVrVtTXxhZ